# Generated by Django 2.0.2 on 2018-12-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avgle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Avgle',
            },
        ),
        migrations.CreateModel(
            name='AvgleQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'AvgleQuery',
            },
        ),
        migrations.CreateModel(
            name='Popjav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Popjav',
            },
        ),
        migrations.CreateModel(
            name='PopjavQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'PopjavQuery',
            },
        ),
        migrations.CreateModel(
            name='Pornhub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Pornhub',
            },
        ),
        migrations.CreateModel(
            name='PornhubQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'PornhubQuery',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'db_table': 'Query',
            },
        ),
        migrations.CreateModel(
            name='Redtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Redtube',
            },
        ),
        migrations.CreateModel(
            name='RedtubeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'RedtubeQuery',
            },
        ),
        migrations.CreateModel(
            name='Thisav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Thisav',
            },
        ),
        migrations.CreateModel(
            name='ThisavQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'ThisavQuery',
            },
        ),
        migrations.CreateModel(
            name='Tube85',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Tube85',
            },
        ),
        migrations.CreateModel(
            name='Tube85Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Tube85Query',
            },
        ),
        migrations.CreateModel(
            name='Xvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Xvideos',
            },
        ),
        migrations.CreateModel(
            name='XvideosQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'XvideosQuery',
            },
        ),
        migrations.CreateModel(
            name='Youporn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Youporn',
            },
        ),
        migrations.CreateModel(
            name='YoupornQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'YoupornQuery',
            },
        ),
    ]
