# Generated by Django 2.0.2 on 2018-12-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgle',
            name='site',
        ),
        migrations.RemoveField(
            model_name='avglequery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='popjav',
            name='site',
        ),
        migrations.RemoveField(
            model_name='popjavquery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='pornhub',
            name='site',
        ),
        migrations.RemoveField(
            model_name='pornhubquery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='redtube',
            name='site',
        ),
        migrations.RemoveField(
            model_name='redtubequery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='thisav',
            name='site',
        ),
        migrations.RemoveField(
            model_name='thisavquery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tube85',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tube85query',
            name='site',
        ),
        migrations.RemoveField(
            model_name='xvideos',
            name='site',
        ),
        migrations.RemoveField(
            model_name='xvideosquery',
            name='site',
        ),
        migrations.RemoveField(
            model_name='youporn',
            name='site',
        ),
        migrations.RemoveField(
            model_name='youpornquery',
            name='site',
        ),
    ]
