# Generated by Django 2.0.2 on 2018-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgleQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'AvgleQuery',
            },
        ),
        migrations.CreateModel(
            name='PopjavQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'PopjavQuery',
            },
        ),
        migrations.CreateModel(
            name='PornhubQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'PornhubQuery',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'db_table': 'Query',
            },
        ),
        migrations.CreateModel(
            name='RedtubeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'RedtubeQuery',
            },
        ),
        migrations.CreateModel(
            name='ThisavQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'ThisavQuery',
            },
        ),
        migrations.CreateModel(
            name='Tube85Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Tube85Query',
            },
        ),
        migrations.CreateModel(
            name='XvideosQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'XvideosQuery',
            },
        ),
        migrations.CreateModel(
            name='YoupornQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'YoupornQuery',
            },
        ),
    ]
